version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tchat-server
    restart: unless-stopped
    volumes:
      - ./server/chatterCount.json:/app/chatterCount.json
    networks:
      - tchat-network

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tchat-tunnel
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - tchat-network
    depends_on:
      - server

networks:
  tchat-network:
    driver: bridge
